# Use a more stable base image
FROM python:3.11-windowsservercore-ltsc2022

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container
COPY . /app

RUN pip install llama-cpp-python

# Upgrade pip to the latest version
RUN python -m pip install --upgrade pip

# Install build tools to work with llama-cpp-python
RUN pip install --no-cache-dir windows-build-tools

# Pre-install setuptools-scm
RUN pip install --no-cache-dir setuptools-scm

# Provide fallback version
ENV SETUPTOOLS_SCM_PRETEND_VERSION=0.1.0

# Install all dependencies specified in requirements.txt
RUN pip install --no-cache-dir .[all,dev]

# Run tests using pytest
CMD ["pytest", "-vvv"]

# # Use the official Python image for Windows Server Core
# FROM python:3.12-windowsservercore-ltsc2022

# # Set the working directory
# WORKDIR /app

# # Copy the current directory contents into the container
# COPY . /app

# # Upgrade pip to the latest version
# RUN python -m pip install --upgrade pip

# # Pre-install setuptools-scm
# RUN pip install --no-cache-dir setuptools-scm

# # Provide fallback version
# ENV SETUPTOOLS_SCM_PRETEND_VERSION=0.1.0

# # Install all dependencies specified in requirements.txt
# RUN pip install --no-cache-dir .[all,dev]

# # Run tests using pytest
# CMD ["pytest", "-vvv"]
