[pytest]
testpaths = tests
pythonpath = ., src

# run stresstests with `pytest -v -m stress`
markers = 
    stress: marks tests as stress tests
    requires_display: marks tests that require a display
addopts = -v -m "not stress"